# Generated by Django 5.2.9 on 2026-01-03 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['parent_block_id', 'position']},
        ),
    ]
