# Generated by Django 5.2.9 on 2026-01-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_block_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='position',
            field=models.CharField(default='', max_length=32),
        ),
    ]
