# Generated by Django 5.2.9 on 2026-01-09 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_page_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='page',
            name='icon',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
