# Generated by Django 5.2.9 on 2026-01-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_page_favorite_page_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='icon',
            field=models.CharField(blank=True, default='lucide:file', max_length=80),
        ),
    ]
