# Generated by Django 5.2.9 on 2026-01-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_page_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='type',
            field=models.CharField(choices=[('p', 'Paragraph'), ('h1', 'Heading 1'), ('h2', 'Heading 2'), ('h3', 'Heading 3'), ('ul', 'Bulleted List'), ('ol', 'Numbered List'), ('cb', 'Checkbox'), ('img', 'Image'), ('div', 'Divider'), ('code', 'Code')], default='p', max_length=20),
        ),
    ]
