# Generated by Django 5.2.9 on 2026-01-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_block_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='kind',
            field=models.CharField(choices=[('block', 'Block'), ('row', 'Row'), ('column', 'Column')], default='block', max_length=10),
        ),
        migrations.AddField(
            model_name='block',
            name='layout',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='block',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='block',
            index=models.Index(fields=['page', 'kind', 'parent_block', 'position'], name='core_block_page_id_1b58ae_idx'),
        ),
    ]
