# Generated by Django 5.2.9 on 2026-01-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_block_kind_block_layout_block_width_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='props',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
