# Generated by Django 5.2.9 on 2026-01-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_block_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='favorite_position',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True),
        ),
    ]
