# Generated by Django 5.2.9 on 2026-01-27 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_page_collaboration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='page',
        ),
        migrations.RemoveField(
            model_name='block',
            name='parent_block',
        ),
        migrations.RenameIndex(
            model_name='pageauditlog',
            new_name='core_pageau_page_id_515208_idx',
            old_name='core_pageaud_page_id_56d1b8_idx',
        ),
        migrations.RenameIndex(
            model_name='pagecollaborator',
            new_name='core_pageco_page_id_9eec03_idx',
            old_name='core_pagecoll_page_id_6c83b2_idx',
        ),
        migrations.RenameIndex(
            model_name='pagecollaborator',
            new_name='core_pageco_page_id_83ce3c_idx',
            old_name='core_pagecoll_page_id_b1cb09_idx',
        ),
        migrations.RenameIndex(
            model_name='pageinvite',
            new_name='core_pagein_page_id_9deffb_idx',
            old_name='core_pageinv_page_id_1e7f2c_idx',
        ),
        migrations.RenameIndex(
            model_name='pageinvite',
            new_name='core_pagein_invitee_39b41a_idx',
            old_name='core_pageinv_invitee__1d5d9a_idx',
        ),
        migrations.RenameIndex(
            model_name='pageinvite',
            new_name='core_pagein_expires_3877e0_idx',
            old_name='core_pageinv_expires_21b64b_idx',
        ),
        migrations.DeleteModel(
            name='Block',
        ),
    ]
