# Generated by ChatGPT on 2026-01-29
from django.db import migrations, models
import django.db.models.deletion
import uuid
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_page_favorite_m2m"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentThread",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("doc_node_id", models.CharField(db_index=True, max_length=128)),
                ("resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="comment_threads_created", to=settings.AUTH_USER_MODEL)),
                ("page", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comment_threads", to="core.page")),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("author", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="comments", to=settings.AUTH_USER_MODEL)),
                ("thread", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="core.commentthread")),
            ],
        ),
        migrations.AddIndex(
            model_name="commentthread",
            index=models.Index(fields=["page", "doc_node_id", "updated_at"], name="core_commen_page_id_5fd980_idx"),
        ),
        migrations.AddIndex(
            model_name="commentthread",
            index=models.Index(fields=["page", "resolved"], name="core_commen_page_id_2b57c7_idx"),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(fields=["thread", "created_at"], name="core_commen_thread__b3d33c_idx"),
        ),
    ]
